name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  Build:
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x86
            env: Windows
          - os: windows-latest
            arch: x64
            env: Windows
          - os: ubuntu-20.04
            arch: x64
            env: Linux
          - os: ubuntu-20.04
            arch: x86
            env: Linux
          - os: macos-11
            arch: x64
            env: Mac

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.env }}
      RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Directories"
        run: mkdir -p output

      - name: "Produce Output"
        run: echo "${{ matrix.env }}-${{ matrix.arch }}" > output/output.txt

      - name: Result
        run: ls -R output

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.env }}-${{ matrix.arch }}
          path: |
            output/*

      - name: Pack
        if: ${{ env.RELEASE == 'true' }}
        run: |
          cd output
          tar -czf output-${{ matrix.env }}-${{ matrix.arch }}.tar.gz *

      - name: Release
        uses: ncipollo/release-action@v1.11.2
        if: ${{ env.RELEASE == 'true' }}
        with:
          artifacts: output/output-${{ matrix.env }}-${{ matrix.arch }}.tar.gz
          allowUpdates: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          skipIfReleaseExists: true
